In [2]:
# import googleapiclient.discovery
# import pandas as pd
# from urllib.parse import urlparse, parse_qs

# api_service_name = "youtube"
# api_version = "v3"
# DEVELOPER_KEY = "AIzaSyC1YUwsMt-dRKwU1WRJ9YUZZewj7eNjVZQ"  # Replace with your actual YouTube Data API v3 key
# youtube = googleapiclient.discovery.build(api_service_name, api_version, developerKey=DEVELOPER_KEY)

# video_link = input("Enter the YouTube Video Link: ")
# num_comments = int(input("Enter the number of comments to fetch: "))  # Ask user for the number of comments

# parsed_url = urlparse(video_link)
# video_id = parse_qs(parsed_url.query).get("v")
# if video_id:
#     video_id = video_id[0]

#     request = youtube.commentThreads().list(
#         part="snippet",
#         videoId=video_id,
#         maxResults=min(num_comments, 100)  # Limit to 100 comments per request
#     )
#     response = request.execute()

#     comments = []
#     for item in response['items']:
#         comment = item['snippet']['topLevelComment']['snippet']
#         comments.append([
#             comment['authorDisplayName'],
#             comment['publishedAt'],
#             comment['updatedAt'],
#             comment['likeCount'],
#             comment['textDisplay']
#         ])

#     df = pd.DataFrame(comments, columns=['author', 'published_at', 'updated_at', 'like_count', 'text'])

#     csv_filename = "youtube_comments.csv"
#     df.to_csv(csv_filename, index=False)
# else:
#     print("Invalid YouTube video link.")

In [3]:
import googleapiclient.discovery
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from urllib.parse import urlparse, parse_qs

api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = "AIzaSyC1YUwsMt-dRKwU1WRJ9YUZZewj7eNjVZQ"
youtube = googleapiclient.discovery.build(api_service_name, api_version, developerKey=DEVELOPER_KEY)

video_link = input("Enter the YouTube Video Link: ")

parsed_url = urlparse(video_link)
video_id = parse_qs(parsed_url.query).get("v")
if video_id:
    video_id = video_id[0]

    request = youtube.commentThreads().list(
        part="snippet",
        videoId=video_id,
        maxResults=500
    )
    response = request.execute()

    comments = []
    for item in response['items']:
        comment = item['snippet']['topLevelComment']['snippet']
        comments.append([
            comment['authorDisplayName'],
            comment['publishedAt'],
            comment['updatedAt'],
            comment['likeCount'],
            comment['textDisplay']
        ])

    df = pd.DataFrame(comments, columns=['author', 'published_at', 'updated_at', 'like_count', 'text'])

    csv_filename = "youtube_comments.csv"
    df.to_csv(csv_filename, index=False)
else:
    print("Invalid YouTube video link.")

Enter the YouTube Video Link: https://www.youtube.com/watch?v=X0tOpBuYasI&t=40s

In [4]:
dataset = pd.read_csv('youtube_comments.csv')

In [5]:
dataset.shape

(100, 5)

In [6]:
dataset.head(10)

,author,published_at,updated_at,like_count,text
0,Anway Pradhan,2023-08-15T08:35:21Z,2023-08-15T08:35:21Z,1,&quot;Destroyer of destructive power and savio...
1,Lars Frost,2023-08-12T22:04:49Z,2023-08-12T22:04:49Z,0,"i didnt like the casting, specially the lazy e..."
2,Robert Cerat,2023-08-07T10:25:08Z,2023-08-08T12:21:37Z,1,Predictable outcome. This movie is overrated.
3,Clint Bronson 5,2023-08-05T04:46:01Z,2023-08-05T04:46:01Z,0,Can we take in a minute ON HOW THIS MOVIE BOM...
4,Y D,2023-08-03T13:18:03Z,2023-08-03T13:18:03Z,1,Dwayne Johnson nailed it! Very good DC movie!
5,maya9800,2023-08-02T10:55:23Z,2023-08-02T10:55:23Z,2,Even thou this movie has action and some inter...
6,Tuhin Mondal,2023-07-30T22:57:12Z,2023-07-30T22:57:12Z,0,Fantastic Fantastic Fantastic
7,Christopher Sweeney,2023-07-30T18:57:56Z,2023-07-30T18:57:56Z,1,....and of course the conflict of the protagon...
8,Christopher Sweeney,2023-07-30T18:56:43Z,2023-07-30T18:56:43Z,2,Also appreciate the looks of utter FEAR on vil...
9,Christopher Sweeney,2023-07-30T18:54:02Z,2023-07-30T18:54:02Z,2,...also filled with outstanding and excellent ...

In [7]:
dataset.drop(columns = 'author',axis = 1, inplace = True)

In [8]:
dataset.drop(columns = 'published_at',axis = 1, inplace = True)

In [9]:
dataset.drop(columns = 'updated_at',axis = 1, inplace = True)

In [10]:
dataset.drop(columns = 'like_count',axis = 1, inplace = True)

In [11]:
print(dataset)

                                                 text
0   &quot;Destroyer of destructive power and savio...
1   i didnt like the casting, specially the lazy e...
2       Predictable outcome. This movie is overrated.
3   Can we take in a minute ON HOW THIS  MOVIE BOM...
4       Dwayne Johnson nailed it! Very good DC movie!
..                                                ...
95  To much woke….. hollywood destroys itself insi...
96  Who approved this movie???<br>Storyline and sc...
97                                Saviour all the way
98  When you see &#39;Black Adam&#39; for the 2nd ...
99  I still don&#39;t know why people saying Black...

[100 rows x 1 columns]

In [12]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from vaderSentiment) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->vaderSentiment) (2023.7.22)
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [13]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer  # Import the SentimentIntensityAnalyzer class
import nltk
nltk.download('vader_lexicon')
sentiments = SentimentIntensityAnalyzer()
dataset["Positive"] = [sentiments.polarity_scores(i)["pos"] for i in dataset["text"]]
dataset["Negative"] = [sentiments.polarity_scores(i)["neg"] for i in dataset["text"]]
dataset["Neutral"] = [sentiments.polarity_scores(i)["neu"] for i in dataset["text"]]
dataset['Compound'] = [sentiments.polarity_scores(i)["compound"] for i in dataset["text"]]
score = dataset["Compound"].values
sentiment = []
for i in score:
    if i >= 0.05 :
        sentiment.append('Positive')
    elif i <= -0.05 :
        sentiment.append('Negative')
    else:
        sentiment.append('Neutral')
dataset["Sentiment"] = sentiment
dataset.head()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

,text,Positive,Negative,Neutral,Compound,Sentiment
0,&quot;Destroyer of destructive power and savio...,0.316,0.171,0.513,0.5267,Positive
1,"i didnt like the casting, specially the lazy e...",0.064,0.218,0.718,-0.9459,Negative
2,Predictable outcome. This movie is overrated.,0.000,0.000,1.000,0.0000,Neutral
3,Can we take in a minute ON HOW THIS MOVIE BOM...,0.000,0.000,1.000,0.0000,Neutral
4,Dwayne Johnson nailed it! Very good DC movie!,0.350,0.000,0.650,0.5827,Positive

In [14]:
data_new=dataset.drop(['Positive','Negative','Neutral','Compound'],axis=1)
data_new.head()

                                                text Sentiment
0  &quot;Destroyer of destructive power and savio...  Positive
1  i didnt like the casting, specially the lazy e...  Negative
2      Predictable outcome. This movie is overrated.   Neutral
3  Can we take in a minute ON HOW THIS  MOVIE BOM...   Neutral
4      Dwayne Johnson nailed it! Very good DC movie!  Positive

In [15]:
from sklearn.preprocessing import LabelEncoder
from sklearn.utils import resample
from sklearn.feature_extraction.text import CountVectorizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer

from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer, LancasterStemmer
from nltk.stem.snowball import SnowballStemmer
from nltk.corpus import stopwords
from nltk.corpus import wordnet
import string
from string import punctuation

In [16]:
import nltk
import re
nltk.download('stopwords')
stop_words = stopwords.words('english')
porter_stemmer = PorterStemmer()
lancaster_stemmer = LancasterStemmer()
snowball_stemer = SnowballStemmer(language="english")
lzr = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [17]:
def text_processing(text):
    text = text.lower()

    text = re.sub(r'\n',' ', text)

    text = re.sub('[%s]' % re.escape(punctuation), "", text)

    text = re.sub("^a-zA-Z0-9$,.", "", text)

    text = re.sub(r'\s+', ' ', text, flags=re.I)

    text = re.sub(r'\W', ' ', text)

    text = ' '.join([word for word in word_tokenize(text) if word not in stop_words])

    text=' '.join([lzr.lemmatize(word) for word in word_tokenize(text)])

    return text

In [18]:
import nltk
nltk.download('punkt')
nltk.download('omw-1.4')
nltk.download('wordnet')
data_copy = data_new.copy()
data_copy.Comment = data_copy.text.apply(lambda text: text_processing(text))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package wordnet to /root/nltk_data...
<ipython-input-18-ebc3462b56ca>:6: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  data_copy.Comment = data_copy.text.apply(lambda text: text_processing(text))

In [19]:
le = LabelEncoder()
data_copy['Sentiment'] = le.fit_transform(data_copy['Sentiment'])

In [20]:
processed_data = {
    'Sentence':data_copy.Comment,
    'Sentiment':data_copy['Sentiment']
}

processed_data = pd.DataFrame(processed_data)
processed_data.head()

                                            Sentence  Sentiment
0  quotdestroyer destructive power savior humanit...          2
1  didnt like casting specially lazy eyed bad act...          0
2                predictable outcome movie overrated          1
3  take minute movie bombed ideology movie inking...          1
4                dwayne johnson nailed good dc movie          2

In [21]:
processed_data['Sentiment'].value_counts()

2    47
1    33
0    20
Name: Sentiment, dtype: int64

In [22]:
df_neutral = processed_data[(processed_data['Sentiment']==1)]
df_negative = processed_data[(processed_data['Sentiment']==0)]
df_positive = processed_data[(processed_data['Sentiment']==2)]

df_negative_upsampled = resample(df_negative,
                                 replace=True,
                                 n_samples= 205,
                                 random_state=42)

df_neutral_upsampled = resample(df_neutral,
                                 replace=True,
                                 n_samples= 205,
                                 random_state=42)

final_data = pd.concat([df_negative_upsampled,df_neutral_upsampled,df_positive])

In [23]:
final_data['Sentiment'].value_counts()

0    205
1    205
2     47
Name: Sentiment, dtype: int64

In [24]:
corpus = []
for sentence in final_data['Sentence']:
    corpus.append(sentence)
corpus[0:5]

['movie suck',
 'much woke hollywood destroys inside',
 'disappointing movie hearing jay kanye wtt song',
 'personally didn39t see problem movie wasn39t extremely major hated disliked movie couple thing confused still think movie good',
 'movie crappy killed dcu witcher brbrgotta record']

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()
y = final_data.iloc[:, -1].values

In [26]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

array([[62,  0,  0],
       [ 0, 59,  1],
       [ 2,  4, 10]])

In [28]:
nb_score = accuracy_score(y_test, y_pred)
print('accuracy',nb_score)

accuracy 0.9492753623188406

In [29]:
import pickle
filename = 'comment_analyzer.sav'
pickle.dump(classifier, open(filename, 'wb'))
loaded_model = pickle.load(open('comment_analyzer.sav', 'rb'))